configure: Replace use of '-o' with '||' [SC2166]

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -181,7 +181,7 @@ do
          LUA_LIBDIR_SET=yes
          CFLAGS="$CFLAGS -ggdb"
       fi
-      if [ "$OSPRESET" = "freebsd" -o "$OSPRESET" = "openbsd" ]; then
+      if [ "$OSPRESET" = "freebsd" ] || [ "$OSPRESET" = "openbsd" ]; then
          LUA_INCDIR="/usr/local/include/lua51"
          LUA_INCDIR_SET=yes
          CFLAGS="-Wall -fPIC -I/usr/local/include"
@@ -236,7 +236,7 @@ do
    --lua-version|--with-lua-version)
       [ -n "$value" ] || die "Missing value in flag $key."
       LUA_VERSION="$value"
-      [ "$LUA_VERSION" = "5.1" -o "$LUA_VERSION" = "5.2" -o "$LUA_VERSION" = "5.3" ] || die "Invalid Lua version in flag $key."
+      [ "$LUA_VERSION" = "5.1" ] || [ "$LUA_VERSION" = "5.2" ] || [ "$LUA_VERSION" = "5.3" ] || die "Invalid Lua version in flag $key."
       LUA_VERSION_SET=yes
       ;;
    --with-lua)
@@ -425,7 +425,7 @@ then
    else
       interp="Lua";
    fi
-   if [ "$LUA_DIR_SET" -o "$LUA_BINDIR_SET" ]; then
+   if [ "$LUA_DIR_SET" ] || [ "$LUA_BINDIR_SET" ]; then
       where="$LUA_BINDIR";
    else
       where="\$PATH";
